# Generated by Django 4.1.2 on 2023-01-03 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0002_booking_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='NPersons',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
