# Generated by Django 4.1.2 on 2023-01-03 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0003_alter_booking_npersons'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='Email',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
