# Generated by Django 4.1.2 on 2022-12-30 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='carrental',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RImage', models.ImageField(blank=True, null=True, upload_to='Profile')),
                ('RModel', models.CharField(blank=True, max_length=30, null=True)),
                ('RPerHourRate', models.IntegerField(blank=True, null=True)),
                ('RPerDay', models.IntegerField(blank=True, null=True)),
                ('RLeasing', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='carsale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SImage', models.ImageField(blank=True, null=True, upload_to='Profile')),
                ('SModel', models.CharField(blank=True, max_length=30, null=True)),
                ('SBrand', models.CharField(blank=True, max_length=30, null=True)),
                ('SPrice', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
