# Generated by Django 4.1.2 on 2023-01-01 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0004_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carsale',
            name='SPrice',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
