# Generated by Django 4.1.2 on 2023-01-02 03:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0005_alter_carsale_sprice'),
    ]

    operations = [
        migrations.DeleteModel(
            name='carrental',
        ),
        migrations.DeleteModel(
            name='carsale',
        ),
    ]
