# Generated by Django 4.1.2 on 2023-01-02 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0007_booking_menudb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menudb',
            name='Description',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
