# Generated by Django 4.1.2 on 2023-01-02 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0008_alter_menudb_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='menudb',
            name='Image',
            field=models.ImageField(blank=True, null=True, upload_to='Profile'),
        ),
    ]
