# Generated by Django 4.1.2 on 2023-01-02 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0009_menudb_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='cdb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Category_Name', models.CharField(blank=True, max_length=30, null=True)),
                ('Description', models.CharField(blank=True, max_length=30, null=True)),
                ('Image', models.ImageField(blank=True, null=True, upload_to='Profile')),
            ],
        ),
        migrations.CreateModel(
            name='pdb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Category_Name', models.CharField(blank=True, max_length=30, null=True)),
                ('Product_Name', models.CharField(blank=True, max_length=30, null=True)),
                ('Product_Price', models.IntegerField(blank=True, null=True)),
                ('Quantity', models.IntegerField(blank=True, null=True)),
                ('Image', models.ImageField(blank=True, null=True, upload_to='Profile')),
            ],
        ),
        migrations.DeleteModel(
            name='booking',
        ),
        migrations.DeleteModel(
            name='menudb',
        ),
    ]
