# Generated by Django 4.1.2 on 2023-01-02 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0011_rename_admindb_staffdb'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffdb',
            name='Confirm_Password',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
