# Generated by Django 4.1.2 on 2023-01-03 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0013_booking_contact'),
    ]

    operations = [
        migrations.DeleteModel(
            name='booking',
        ),
        migrations.DeleteModel(
            name='contact',
        ),
    ]
